name = "worker-solid"
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

rules = [{ type = "ESModule", globs = ["**/*.js", "**/*.mjs"] }]

[site]
bucket = ".output/public"
